### PR TITLE
fix docker issue. move into its own routes.

### PR DESCRIPTION
**Pull request by nsnguyen**
image

moving into routes for cleaner implementation.
image

### CODE REVIEW

**Comment by martyboggs** [comment]
You need render_template in main.py so that the index.html file loads.

`from flask import Flask, url_for, render_template, request, redirect`

**Comment by martyboggs** [comment]
I had also change the Flask() command to get the right templates path:

`app = Flask(__name__, template_folder='../templates')`

**Review by martyboggs — APPROVED** [review]
5/5 stars!

**Comment by nsnguyen** [comment]
sorry, i didn't get time to look into this but saw you made the change already 👍

**Pull request merged**
